using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UIElements;
using Photon.Pun;
using Cinemachine;

public class multiEffectPlayer : MonoBehaviourPunCallbacks
{
    private static readonly Joycon.Button[] m_buttons =
    Enum.GetValues(typeof(Joycon.Button)) as Joycon.Button[];

    List<Joycon> joyconList;
    private Joycon joyconL;     // ï¿½ï¿½ï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½
    private Joycon joyconR;     // ï¿½Eï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½

    private Vector3 gyroR = Vector3.zero;
    private Vector3 gyroL = Vector3.zero;

    [SerializeField]
    private new Rigidbody rigidbody = null;
    public CinemachineVirtualCamera virtualCamera = null;

    [SerializeField]
    private Vector3 rotateOffset = Vector3.zero;    // ï¿½Wï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ÌŒë·ï¿½ğ–³ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½tï¿½Zï¿½bï¿½g

    [SerializeField]
    private float minSpeed = 5.0f;      // ï¿½Å’á‘¬ï¿½x
    [SerializeField]
    private float maxSpeed = 100.0f;    // ï¿½Åï¿½ï¿½ï¿½ï¿½x
    [SerializeField]
    private float speedRate = 0.01f;    // ï¿½Xï¿½sï¿½[ï¿½hï¿½{ï¿½ï¿½
    [SerializeField]
    private float speed = 0.0f;         // ï¿½ï¿½ï¿½İ‚Ì‘ï¿½ï¿½x

    [SerializeField]
    private Vector3 totalGyroR;     // ï¿½Eï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ÌŒXï¿½ï¿½ï¿½Ìï¿½ï¿½vï¿½l
    [SerializeField]
    private Vector3 totalGyroL;     // ï¿½ï¿½ï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ÌŒXï¿½ï¿½ï¿½Ìï¿½ï¿½vï¿½l

    Vector2 startJoyLRotateY = Vector2.zero;      // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ÌƒXï¿½^ï¿½[ï¿½gï¿½ï¿½ï¿½ÌŠpï¿½x ï¿½ï¿½ï¿½ï¿½ï¿½ÓIï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½0.0ï¿½ï¿½ï¿½ï¿½1.0 yï¿½ï¿½ï¿½ï¿½0.0ï¿½ï¿½ï¿½ï¿½-90.0ï¿½É‚È‚ï¿½Ü‚ï¿½
    Vector2 startJoyRRotateY = Vector2.zero;      // ï¿½Eï¿½Wï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ÌƒXï¿½^ï¿½[ï¿½gï¿½ï¿½ï¿½ÌŠpï¿½x


    [SerializeField]
    private float updownRate = 0.01f;       // ï¿½ã¸ï¿½Eï¿½ï¿½ï¿½~ï¿½Ì”{ï¿½ï¿½
    [SerializeField]
    private float leftlightRate = 0.01f;    // ï¿½ï¿½ï¿½Eï¿½Ú“ï¿½ï¿½Ì”{ï¿½ï¿½
    [SerializeField]
    private float rollRate = 0.01f;         // ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½]ï¿½Ì”{ï¿½ï¿½
    [SerializeField]
    private bool isRotate = false;          // ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Å‰ï¿½]ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½ï¿½\ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
    [SerializeField]
    private float brakePower = 1.0f;        // ï¿½uï¿½ï¿½ï¿½[ï¿½Lï¿½ï¿½
    bool brakeFlag = false;

    [SerializeField]
    private float rollControlTime = 1.0f;   // ï¿½pï¿½ï¿½ï¿½ğ’¼‚ï¿½ï¿½Ü‚Å‚Ìï¿½ï¿½ï¿½
    private Coroutine rollControlCoroutine = null;

    [SerializeField]
    private float minFov = 60.0f;
    [SerializeField]
    private float maxFov = 100.0f;
    [SerializeField]
    private float addFov = 0.4f;
    [SerializeField]
    private float subFov = 0.2f;


    [SerializeField]
    private GameObject particleObject;

    [SerializeField]
    private ParticleSystem testParticle;

    // Start is called before the first frame update
    void Start()
    {
        // ï¿½Wï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
        joyconList = JoyconManager.Instance.j;
        if (joyconList == null || joyconList.Count == 0)
        {
            Debug.Log("joyconï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
        }
        else
        {
            // ï¿½ï¿½ï¿½Eï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ï¿½Tï¿½ï¿½
            joyconL = joyconList.Find(c => c.isLeft);
            joyconR = joyconList.Find(c => !c.isLeft);
        }
        // ï¿½Xï¿½sï¿½[ï¿½hï¿½ï¿½ï¿½Å’ï¿½Xï¿½sï¿½[ï¿½hï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½
        speed = minSpeed;
        rigidbody.linearVelocity = transform.forward * speed;
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Éƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½^ï¿½Oï¿½ï¿½tï¿½^ï¿½ï¿½ï¿½ï¿½ > playerï¿½^ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Äï¿½ï¿½@ï¿½ÉƒJï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (photonView.IsMine)
        {
            tag = "Player";
            enabled = true;
        }
        else
        {
            tag = "Untagged";
            enabled = false;
        }

    }

    // Update is called once per frame
    void Update()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½É‚Ì‚İï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
        if (photonView.IsMine)
        {
            gyroR = Vector3.zero;
            gyroL = Vector3.zero;
            if (joyconList != null && joyconList.Count != 0)
            {
                // ï¿½Wï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½Ì‘Oï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Æ‚ÌŠpï¿½xï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
                gyroR = joyconR.GetGyro();
                gyroL = joyconL.GetGyro();
            }
            else
            {
                totalGyroL = Vector3.zero;
                totalGyroR = Vector3.zero;
            }

            // ï¿½fï¿½oï¿½bï¿½Nï¿½pï¿½ÌƒLï¿½[ï¿½ï¿½ï¿½ï¿½
            float keyRate = 100.0f;
            if (Input.GetKey(KeyCode.W))
            {
                gyroR.x = -keyRate;
                gyroL.x = keyRate;
            }
            if (Input.GetKey(KeyCode.S))
            {
                gyroR.x = keyRate;
                gyroL.x = -keyRate;
            }
            if (Input.GetKey(KeyCode.A))
            {
                gyroR.z = keyRate;
                gyroL.z = -keyRate;
            }
            if (Input.GetKey(KeyCode.D))
            {
                gyroR.z = -keyRate;
                gyroL.z = keyRate;
            }
            if (Input.GetKey(KeyCode.Q))
            {
                gyroR.y = -keyRate;
                gyroL.y = keyRate;
            }
            if (Input.GetKey(KeyCode.E))
            {
                gyroR.y = keyRate;
                gyroL.y = -keyRate;
            }


            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½çŒ»ï¿½İ‚ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
            totalGyroR += gyroR;
            totalGyroL += gyroL;


            // ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒXï¿½ï¿½ï¿½Í–ï¿½ï¿½ï¿½
            if (gyroR.x < rotateOffset.x && gyroR.x > -rotateOffset.x)
            {
                gyroR.x = 0.0f;
            }
            if (gyroR.y < rotateOffset.y && gyroR.y > -rotateOffset.y)
            {
                gyroR.y = 0.0f;
            }
            if (gyroR.z < rotateOffset.z && gyroR.z > -rotateOffset.z)
            {
                gyroR.z = 0.0f;
            }
            if (gyroL.x < rotateOffset.x && gyroL.x > -rotateOffset.x)
            {
                gyroL.x = 0.0f;
            }
            if (gyroL.y < rotateOffset.y && gyroL.y > -rotateOffset.y)
            {
                gyroL.y = 0.0f;
            }
            if (gyroL.z < rotateOffset.z && gyroL.z > -rotateOffset.z)
            {
                gyroL.z = 0.0f;
            }

            // ï¿½ï¿½ï¿½Eï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ÌŠpï¿½xï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ÌƒWï¿½ï¿½ï¿½Cï¿½Rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ğ‚Ë‚ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½iï¿½Aï¿½Nï¿½Zï¿½ï¿½ï¿½jï¿½ğ”»’ï¿½
            float offsetGyroX = totalGyroL.x + totalGyroR.x;

            // ï¿½Nï¿½ï¿½ï¿½bï¿½`(ï¿½ï¿½ï¿½ï¿½)
            if (offsetGyroX < -20.0f)
            {
                speed += offsetGyroX * (-1.0f) * speedRate;
                virtualCamera.m_Lens.FieldOfView += addFov;
                if (virtualCamera.m_Lens.FieldOfView > maxFov)
                {
                    virtualCamera.m_Lens.FieldOfView = maxFov;
                }
            }
            // FOVï¿½ï¿½ï¿½ï¿½ï¿½Æ‚É–ß‚ï¿½
            else if (virtualCamera.m_Lens.FieldOfView > minFov)
            {
                virtualCamera.m_Lens.FieldOfView += -subFov;
                if (virtualCamera.m_Lens.FieldOfView <= minFov)
                {
                    virtualCamera.m_Lens.FieldOfView = minFov;
                }
            }

            if (Input.GetKey(KeyCode.Space))
            {
                speed += 0.2f;
                // FOVï¿½ÏXï¿½ï¿½ï¿½ï¿½
                virtualCamera.m_Lens.FieldOfView += addFov;
                if (virtualCamera.m_Lens.FieldOfView > maxFov)
                {
                    virtualCamera.m_Lens.FieldOfView = maxFov;
                }
            }
            // FOVï¿½ï¿½ï¿½ï¿½ï¿½Æ‚É–ß‚ï¿½
            else if (virtualCamera.m_Lens.FieldOfView > minFov)
            {
                virtualCamera.m_Lens.FieldOfView += -subFov;
                if (virtualCamera.m_Lens.FieldOfView <= minFov)
                {
                    virtualCamera.m_Lens.FieldOfView = minFov;
                }
            }

            // ï¿½Å’ï¿½Eï¿½Åï¿½ï¿½ï¿½ï¿½xï¿½`ï¿½Fï¿½bï¿½N
            if (speed < minSpeed)
            {
                speed = minSpeed;
            }
            if (speed > maxSpeed)
            {
                speed = maxSpeed;
            }

            // ï¿½uï¿½ï¿½ï¿½[ï¿½L
            brakeFlag = false;
            if ((joyconR != null && joyconR.GetButton(Joycon.Button.SHOULDER_2)) || Input.GetKey(KeyCode.V))
            {
                brakeFlag = true;
            }

            // ï¿½Wï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
            if ((joyconR != null && joyconR.GetButtonDown(Joycon.Button.SHOULDER_1)) || Input.GetKey(KeyCode.R))
            {
                totalGyroR = Vector3.zero;
                totalGyroL = Vector3.zero;
                transform.rotation = Quaternion.Euler(transform.eulerAngles.x, transform.eulerAngles.y, 0.0f);
                speed = minSpeed;
            }
        }

    }

    private void FixedUpdate()
    {
        if (Input.GetMouseButtonDown(1))
        {
            Vector3 position = transform.position + transform.forward * 100;

            Vector3 spwanPos = new Vector3(transform.position.x, transform.position.y, transform.position.z) + transform.forward * 500;
            particleObject = PhotonNetwork.Instantiate("TestParticleSystem", spwanPos, transform.rotation);
        }

        //ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½   
        if (photonView.IsMine)
        {
            var vec = (transform.forward * speed) - rigidbody.linearVelocity;
            rigidbody.AddForce(vec, ForceMode.Force);

            if (brakeFlag)
            {
                speed -= brakePower;
                if (speed < 0.0f)
                {
                    speed = 0.0f;
                }
            }

            isRotate = false;

            // ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È‚ï¿½ã¸ï¿½Eï¿½ï¿½ï¿½~
            if (totalGyroL.x > 50.0f || totalGyroL.x < -50.0f || gyroL.x != 0.0f)
            {
                isRotate = true;
                if (rollControlCoroutine != null)
                {
                    StopCoroutine(rollControlCoroutine);
                    rollControlCoroutine = null;
                }
                float angle = totalGyroL.x * (-1.0f) * updownRate * Time.fixedDeltaTime;
                transform.Rotate(Vector3.right, angle, Space.Self);
                // -180ï¿½ï¿½ï¿½ï¿½180ï¿½Éï¿½ï¿½Kï¿½ï¿½
                float normAngle = Mathf.Repeat(transform.eulerAngles.x + 180.0f, 360.0f) - 180.0f;
                if (normAngle < -85.0f || normAngle > 85.0f)
                {
                    transform.Rotate(Vector3.right, -angle, Space.Self);
                }
            }

            // ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½zï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È‚ç¶ï¿½Eï¿½Ú“ï¿½
            if (totalGyroL.z > 50.0f || totalGyroL.z < -50.0f || gyroL.z != 0.0f)
            {
                isRotate = true;
                if (rollControlCoroutine != null)
                {
                    StopCoroutine(rollControlCoroutine);
                    rollControlCoroutine = null;
                }
                transform.Rotate(Vector3.up, totalGyroL.z * leftlightRate * Time.fixedDeltaTime, Space.World);
                float angle = totalGyroL.z * (-1.0f) * rollRate * Time.fixedDeltaTime;
                transform.Rotate(Vector3.forward, angle, Space.Self);
                // -180ï¿½ï¿½ï¿½ï¿½180ï¿½Éï¿½ï¿½Kï¿½ï¿½
                float normAngle = Mathf.Repeat(transform.eulerAngles.z + 180.0f, 360.0f) - 180.0f;
                if (normAngle < -45.0f || normAngle > 45.0f)
                {
                    transform.Rotate(Vector3.forward, -angle, Space.Self);
                }
            }
            if (!isRotate && (transform.eulerAngles.z > 0.001f || transform.eulerAngles.z < -0.001f) && rollControlCoroutine == null)
            {
                rollControlCoroutine = StartCoroutine(RollAttitudeControl());
            }
        }
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ìpï¿½ï¿½ï¿½ï¿½ß‚ï¿½ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½
    /// </summary>
    /// <returns></returns>
    public IEnumerator RollAttitudeControl()
    {
        // ï¿½ï¿½ï¿½İ‚Ìƒï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒXï¿½ï¿½ï¿½Æï¿½ï¿½íï¿½ÌŒXï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½pï¿½ï¿½ï¿½ğ’¼‚ï¿½ï¿½Nï¿½Hï¿½[ï¿½^ï¿½jï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ì¬
        Quaternion fromQuat = transform.rotation;
        Quaternion toQuat = Quaternion.Euler(transform.eulerAngles.x, transform.eulerAngles.y, 0.0f);
        float nowTime = 0.0f;
        while (true)
        {
            nowTime += Time.fixedDeltaTime;
            Quaternion rot = Quaternion.Slerp(fromQuat, toQuat, nowTime / rollControlTime);
            transform.rotation = rot;
            if (nowTime / rollControlTime >= 1.0f)
            {
                rollControlCoroutine = null;
                yield break;
            }
            yield return new WaitForFixedUpdate();
        }
    }
}
